### ISSUE TITLE
[Rust Activate Mexico City 2017] Índice

### ISSUE THREAD

**Issue by sebasmagri** [rustmx/team#1]
Issue de sombrilla para los items a definir para el evento.
/cc @lasr21 @aio00 @Heeled-Jim @Yulireyji @federicomenaquintero

Referencias

* https://public.etherpad-mozilla.org/p/RustFest
* https://public.etherpad-mozilla.org/p/rustmx-abril-2017

- [ ] Agenda #2
- [ ] Difusión #3
- [ ] Artwork / POP / SWAG #4 
- [ ] Landing Page #6

**Comment by sebasmagri** [comment]
Deberíamos levantar un eventbrite para los registros? usamos el mismo meetup.com? /cc @Heeled-Jim

**Comment by sebasmagri** [comment]
Podemos incluir en el presupuesto algo de viáticos para traer gente de otras ciudades @yulireyji? Yo estaría dispuesto a colaborar para que eso suceda también...

**Comment by lasr21** [comment]
@sebasmagri piensas en traer otra gente como ponente o como asistente, en el caso de de asistentes es mucho más complicado garantizar el recurso para que suceda.

**Comment by sebasmagri** [comment]
@lasr21 me encantaría que puedan mostrar su trabajo acá, pero tal vez las restricciones de tiempo no nos permitan hacerlo... Igual podríamos ver qué podemos reunir para traer a alguno como asistente y fortalecer lazos con las comunidades de fuera de CDMX.

**Comment by Heeled-Jim** [comment]
@sebasmagri apoyo la idea del eventbrite para los registros y ligar dicha cuenta al meetup de Rust MX que coordina @aio00 ¿que les parece? yo apoyo con la landing page :)

@sebasmagri @lasr21 confirmemos a Brian Anderson lo antes posible para el evento, para el hackathon con Gnome, Mozilla cubrió sus gastos, podría manejarse algo parecido para esta ocasión no? y de entrada considerar a Mario García de Chiapas para apoyarlo con sus gastos de transporte no? el es miembro de Rust MX y seguramente vendría como ponente :)
