### ISSUE TITLE
[Rust Activate Mexico City 2017] Artwork / POP

### ISSUE THREAD

**Issue by sebasmagri** [rustmx/team#4]
- [ ] Traducir y/o adaptar materiales de [community resources](https://github.com/rust-community/resources)
- [ ] Pendones
- [ ] Posters
- [ ] Flyers
- [ ] Playeras

**Comment by tuxlan** [comment]
Hola @sebasmagri 
Me parece que puedo ayudar a localizar parte del material de [community resources](https://github.com/rust-community/resources)
Espero que a finales de este mes ya tenga localizado una parte del material.
Saludos
