### ISSUE TITLE
[Rust Activate Mexico City 2017] Formatos de Contacto

### ISSUE THREAD

**Issue by sebasmagri** [rustmx/team#7]
- [x] Formato de Invitación al Evento: para extender invitaciones de manera _oficial_ a grupos de interés como Woman Who Code, Django Girls, etc.
- [x] Formato de solicitud de apoyo en difusión: para solicitar formalmente la difusión del evento en distintos canales a empresas o instituciones con alto tráfico orgánico.

**Comment by sebasmagri** [comment]
@yulireyji @lasr21 tenemos alguna plantilla de este tipo de formatos en MozMX o de eventos anteriores que podamos remixear? Haría falta algún otro formato?

**Comment by yulireyji** [comment]
Hola! Contamos con SocialTIC para difusión.

**Comment by sebasmagri** [comment]
Hola @yulireyji,

Dejo un link a una versión inicial de un correo de contacto para enviarlo a organizaciones de interés:

https://public.etherpad-mozilla.org/p/RustActivate-CartaDeContacto

Saludos,
